version: '3.8'
services:
  api:
    restart: always
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port ${API_PORT} --reload
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - API_PORT=${API_PORT}
      - MONGODB_URL=${MONGODB_URL}

  reverse-proxy:
    restart: always
    build: ./reverse-proxy
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
    tty: true

  db:
    restart: always
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
